name: "Comfo-air"
description: "tries to run the comfoair as a docker container"
version: "0.0.1"
slug: "comfoair-docker"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  3333/tcp: 3333
